- hosts: centos
  tasks:
     - name: Install Dependencies
       yum:
         name: "{{ item }}"
         state: present
       with_items: 
         - nfs-utils
         - python-pip
         - nginx 
         
     
...
